[package]
name = "CFDRust"
version = "0.1.0"
edition = "2021"

[lib]
name = "cfd_rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.15.1", features = ["extension-module"] }
numpy = "0.15.1"
