[package]
name = "cfd_rust"
version = "0.2.0"
edition = "2021"

[lib]
name = "cfd_rust"
# https://github.com/rust-lang/cargo/issues/6659
crate-type = ["lib", "cdylib"]

[dependencies]
ndarray = "0.15.4"
