[package]
name = "cfd_rust"
version = "0.2.0"
edition = "2021"

[lib]
name = "cfd_rust"
# https://github.com/rust-lang/cargo/issues/6659
crate-type = ["lib", "cdylib"]

[dependencies]
pyo3 = { version = "0.15.1", features = ["extension-module"] }
numpy = "0.15.1"
ndarray = "0.15.4"
